FROM oven/bun:1 AS builder
WORKDIR /app
COPY . .
ARG VITE_HOST_URL=deti-tqs-16.ua.pt
RUN bun install --frozen-lockfile
RUN bun run build

FROM nginx:1-alpine
WORKDIR /app
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
