name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: CityConnect-TQS/control-room
          token: ${{ secrets.PRIVATE_TOKEN }}
          submodules: recursive

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Up containers
        env:
          PRODUCTION: true
          CURRENCY_API_KEY: ${{secrets.CURRENCY_API_KEY}}
          JWT_PRIVATE: ${{secrets.JWT_PRIVATE}}
          JWT_PUBLIC: ${{secrets.JWT_PUBLIC}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        run: docker compose -f compose.prod.yaml up -d --build

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: http://staff.localhost
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: "https://www.foo.software,https://www.google.com"
