name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: CityConnect-TQS/control-room
          token: ${{ secrets.PRIVATE_TOKEN }}
          submodules: recursive

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: "${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}"
          restore-keys: ${{ runner.os }}-m2

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Up containers
        env:
          PRODUCTION: true
          CURRENCY_API_KEY: ${{secrets.CURRENCY_API_KEY}}
          JWT_PRIVATE: ${{secrets.JWT_PRIVATE}}
          JWT_PUBLIC: ${{secrets.JWT_PUBLIC}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        run: docker compose -f compose.prod.yaml up -d --build

      - name: Go to staff portal
        run: cd staff-portal

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: http://localhost/staff
          uploadArtifacts: true
          temporaryPublicStorage: true
